### ISSUE TITLE
Invalid multibyte character encoding

### ISSUE THREAD

**Issue by alexandermendes** [alexandermendes/Flask-Z3950#2]
Getting lots of server errors along these lines:

```
Exception on /z3950/search/oclc/html [GET] Traceback (most recent call last):
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/var/www/pybossa/env/local/lib/python2.7/site-packages/Flask_Z3950-0.2.2-py2.7.egg/flask_z3950/view.py", line 61, in search_html
    data = dataset.to_html()
  File "/var/www/pybossa/env/local/lib/python2.7/site-packages/Flask_Z3950-0.2.2-py2.7.egg/flask_z3950/dataset.py", line 46, in to_html
    records = [pymarc.Record(data=r) for r in self.record_data]
  File "build/bdist.linux-x86_64/egg/pymarc/record.py", line 74, in __init__
    utf8_handling=utf8_handling)
  File "build/bdist.linux-x86_64/egg/pymarc/record.py", line 314, in decode_marc
    data = marc8_to_unicode(data, hide_utf8_warnings)
  File "build/bdist.linux-x86_64/egg/pymarc/marc8.py", line 27, in marc8_to_unicode
    raise UnicodeDecodeError("marc8_to_unicode", marc8, 0, len(marc8), "invalid multibyte character encoding")
UnicodeDecodeError: 'marc8_to_unicode' codec can't decode bytes in position 0-16: invalid multibyte character encoding

```

**Comment by alexandermendes** [comment]
UnicodeDecodeErrors caught since v.0.2.3
